# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotenv < Formula
  desc ""
  homepage "https://github.com/levibostian/dotenv"
  version "1.0.0-beta.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/levibostian/dotenv/releases/download/1.0.0-beta.1/dotenv_1.0.0-beta.1_Darwin_x86_64.tar.gz"
    sha256 "a1f4b552d84610029ad17452fd30d92f109fb84a636005d57bd3398f324f87d4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/levibostian/dotenv/releases/download/1.0.0-beta.1/dotenv_1.0.0-beta.1_Linux_x86_64.tar.gz"
    sha256 "3758dd4b798837f4c61bf4f37378897e81fd0ec0860353924d80aee2d33b3f2d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/levibostian/dotenv/releases/download/1.0.0-beta.1/dotenv_1.0.0-beta.1_Linux_arm64.tar.gz"
    sha256 "69567cea5b3945d96a7d0adbe01312b7b6a11b95622af522dafdbf4b558b228c"
  end

  def install
    bin.install "dotenv"
  end
end
