# This file was generated by GoReleaser. DO NOT EDIT.
class Purslane < Formula
  desc ""
  homepage "https://github.com/levibostian/purslane"
  version "1.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/levibostian/Purslane/releases/download/1.4.2/Purslane_1.4.2_Darwin_x86_64.tar.gz"
    sha256 "1d006ef00cdf3c1a517bf4e80161345823c4073d6eee2696341e026373f31ac2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/levibostian/Purslane/releases/download/1.4.2/Purslane_1.4.2_Linux_x86_64.tar.gz"
      sha256 "e0598a70f6e97b8ac01887a6c4b86ef92d065f851ec2d7856a1604c2e114f0bb"
    end
  end

  def install
    bin.install "purslane"
  end
end
