# This file was generated by GoReleaser. DO NOT EDIT.
class Purslane < Formula
  desc ""
  homepage "https://github.com/levibostian/purslane"
  version "1.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/levibostian/Purslane/releases/download/1.3.0/Purslane_1.3.0_Darwin_x86_64.tar.gz"
    sha256 "ab1d8bad9218d44ed40fd1c6bfbc14305a480fe285ebefeee027e51e6931b50b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/levibostian/Purslane/releases/download/1.3.0/Purslane_1.3.0_Linux_x86_64.tar.gz"
      sha256 "3ec375c62356ffd567dc4233d168c00e22da56f1432150cd5ce5adf6522b9334"
    end
  end

  def install
    bin.install "purslane"
  end
end
